//
// Originally created by RUPC on 2024/1/8.
//

#ifndef HARDWARE_DP32G030_TIMER_H
#define HARDWARE_DP32G030_TIMER_H
#include <stdint.h>

// Register offsets
#define TIMERBASE_EN_OFFSET        0x00
#define TIMERBASE_DIV_OFFSET       0x04
#define TIMERBASE_IE_OFFSET        0x10
#define TIMERBASE_IF_OFFSET        0x14
#define TIMERBASE_HIGH_LOAD_OFFSET 0x20
#define TIMERBASE_HIGH_CNT_OFFSET  0x24
#define TIMERBASE_LOW_LOAD_OFFSET  0x30
#define TIMERBASE_LOW_CNT_OFFSET   0x34

//TIMER0
// Base address for TIMERBASE0 peripheral
#define TIMERBASE0_BASE_ADDR 0x40064000

#define TIMERBASE0_EN_ADDR        (TIMERBASE0_BASE_ADDR + TIMERBASE_EN_OFFSET)
#define TIMERBASE0_DIV_ADDR       (TIMERBASE0_BASE_ADDR + TIMERBASE_DIV_OFFSET)
#define TIMERBASE0_IE_ADDR        (TIMERBASE0_BASE_ADDR + TIMERBASE_IE_OFFSET)
#define TIMERBASE0_IF_ADDR        (TIMERBASE0_BASE_ADDR + TIMERBASE_IF_OFFSET)
#define TIMERBASE0_HIGH_LOAD_ADDR (TIMERBASE0_BASE_ADDR + TIMERBASE_HIGH_LOAD_OFFSET)
#define TIMERBASE0_HIGH_CNT_ADDR  (TIMERBASE0_BASE_ADDR + TIMERBASE_HIGH_CNT_OFFSET)
#define TIMERBASE0_LOW_LOAD_ADDR  (TIMERBASE0_BASE_ADDR + TIMERBASE_LOW_LOAD_OFFSET)
#define TIMERBASE0_LOW_CNT_ADDR   (TIMERBASE0_BASE_ADDR + TIMERBASE_LOW_CNT_OFFSET)
#define TIMERBASE0_EN (*(volatile uint32_t *)TIMERBASE0_EN_ADDR)
#define TIMERBASE0_DIV (*(volatile uint32_t *)TIMERBASE0_DIV_ADDR)
#define TIMERBASE0_IE (*(volatile uint32_t *)TIMERBASE0_IE_ADDR)
#define TIMERBASE0_IF (*(volatile uint32_t *)TIMERBASE0_IF_ADDR)
#define TIMERBASE0_HIGH_LOAD (*(volatile uint32_t *)TIMERBASE0_HIGH_LOAD_ADDR)
#define TIMERBASE0_HIGH_CNT (*(volatile uint32_t *)TIMERBASE0_HIGH_CNT_ADDR)
#define TIMERBASE0_LOW_LOAD (*(volatile uint32_t *)TIMERBASE0_LOW_LOAD_ADDR)
#define TIMERBASE0_LOW_CNT (*(volatile uint32_t *)TIMERBASE0_LOW_CNT_ADDR)

#endif //HARDWARE_DP32G030_TIMER_H
